name: Build binaries

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build binaries for ${{ matrix.platform }}-${{ matrix.arch.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - darwin
        arch:
          - suffix: arm64
            name: arm64
          - suffix: x64
            name: amd64

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup node.js runtime
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Download dependencies
        run: npm install

      - name: Build binary using `pkg`
        run: npx pkg mistbigqueryuploader.js --targets "node16-${{ matrix.platform }}-${{ matrix.arch.suffix }}"

      - name: Rename and move built binary
        run: |
          mv mistbigqueryuploader livepeer-mist-bigquery-uploader
          mkdir -p releases/
          tar -czvf "releases/livepeer-mist-bigquery-uploader-${{ matrix.platform }}-${{ matrix.arch.name }}.tar.gz" ./livepeer-mist-bigquery-uploader

      - name: Upload artifacts for processing further in linux
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: releases/
