name: Create release on github

on:
  workflow_run:
    workflows:
      - Build binaries
    types:
      - "completed"

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Download artifacts from build stage
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts
          path: mistbigqueryuploader
      - name: Release to github
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: mistbigqueryuploader
