name: Create release on github

on:
  workflow_run:
    workflows:
      - Build binaries
    types:
      - "completed"

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Download artifacts from build stage
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yaml
          name: release-artifacts
          path: releases/

      - name: Generate sha256 checksum and gpg signatures for release artifacts
        uses: livepeer/action-gh-checksum-and-gpg-sign@latest
        with:
          artifacts-dir: releases
          release-name: ${{ github.event.workflow_run.head_branch }}
          gpg-key: ${{ secrets.CI_GPG_SIGNING_KEY }}
          gpg-key-passphrase: ${{ secrets.CI_GPG_SIGNING_PASSPHRASE }}

      - name: Release to github
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: |
            releases/*
